imports:
    - { resource: menu.yaml}
parameters:
    OAUTH_GITHUB_CLIENT_ID: '%env(OAUTH_GITHUB_CLIENT_ID)%'
    OAUTH_GITHUB_CLIENT_SECRET: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
    OAUTH_GITHUB_CLIENT_REDIRECT_ROUTE: '%env(OAUTH_GITHUB_CLIENT_REDIRECT_ROUTE)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Component/Security/Entity'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Component\Provider\Github\OAuth2GithubClientProviderFactory: ~
    App\Serializer\SerializerFactory: ~
    League\OAuth2\Client\Provider\Github:
        factory: ['@App\Component\Provider\Github\OAuth2GithubClientProviderFactory', 'getProvider']
    Symfony\Component\Serializer\Serializer:
        factory: ['@App\Serializer\SerializerFactory', 'createSerializer']
    
    App\Component\Provider\Google\GoogleApiClientFactory: ~
    
    Google\Service\PeopleService:
        factory: ['@App\Component\Provider\Google\GoogleApiClientFactory', 'createPeopleService']
    
    
    App\Component\Security\DefaultSecurityRoleProvider: ~

    App\Component\Security\AclDiscoveryRegistry:
        lazy: true
        calls: 
            - ['setNamespace', ['App\Controller']]
            - ['setRoleProvider', ['@App\Component\Security\DefaultSecurityRoleProvider']]
    App\Menu\BackMenuBuilder:
        calls:
            - ['setPmm']
            - ['setSecurity']
        
